server:
    port: 9190
spring:
    application:
        name: mock-service
eureka:
  client:
    service-url:
      defaultZone: http://10.82.14.80:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:  
    health:
      show-details: always
# Enable these to debug the Authorization flow
logging:
    level:
      org:
        springframework:
          hibernate: ERROR
          web: DEBUG

    file:
      name: logs/application-debug.log
      max-size: 2MB
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
